### ISSUE TITLE
Error building on Debian Bullseye

### ISSUE THREAD

**Issue by zoof** [pybliographer/python-recode#1]
Is this still supported?  I am hoping to get Pybliographer working as no major distributions still support it and it would be my preferred BibTeX reference manager if I could get it working (there are other alternatives but who wants to install a million dependencies for `jabref`).  But in order to try to build Pybliographer, I need to first build `python-recode`.  When I attempt to build `python-recode`, I get:
```
recodemodule.c:82:3: warning: initialization of ‘PyAsyncMethods *’ from incompatible pointer type ‘int (*)(PyObject *, char *, PyObject *)’ {aka ‘int (*)(struct _object *, char *, struct _object *)’} [-Wincompatible-pointer-types]
   82 |   (setattrfunc)0,                 /*tp_setattr*/
      |   ^
recodemodule.c:82:3: note: (near initialization for ‘PyRecodeRequest_Type.tp_as_async’)
recodemodule.c:83:4: error: ‘cmpfunc’ undeclared here (not in a function)
   83 |   (cmpfunc)0,                     /*tp_compare*/
      |    ^~~~~~~
recodemodule.c:83:12: error: expected ‘}’ before numeric constant
   83 |   (cmpfunc)0,                     /*tp_compare*/
      |            ^
```

Am I missing some dependency or is it going to require a major rewrite to get any of this stack working with a modern distribution?

**Comment by gpoo** [comment]
May you provide more information? It works for me on Ubuntu 21.10 and Python 2.7

**Comment by zoof** [comment]
I see, yes, it built once I installed Python 2.7 -- are there any plans to upgrade this to Python 3?

**Comment by gpoo** [comment]
I would like to see it working with Python 3, but I have not had time to work on the project.
